# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/astronomical',
                'doc_host': 'https://the-engi-nerd.github.io',
                'git_url': 'https://github.com/the-engi-nerd/astronomical',
                'lib_path': 'astronomical'},
  'syms': {'astronomical.core': {'astronomical.core.foo': ('core.html#foo', 'astronomical/core.py')}}}